apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: capiot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: flamware/capiot-api:5
          imagePullPolicy: Always
          env:
            # Explicitly define database credentials and name directly
            # NOTE: Hardcoding sensitive information directly in the Deployment YAML
            # is generally not recommended for production environments.
            # Secrets should be managed using Kubernetes Secrets or a secrets management solution.
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "admin"
            - name: DB_NAME
              value: "capiot"
            - name: POSTGRES_DB
              value: "capiot"
          envFrom:
            # Continue to use envFrom for other secrets and configMap
            - secretRef:
                name: api-secrets
            - configMapRef:
                name: api-configmap
          ports:
            - containerPort: 8080  # Matches Service port
          livenessProbe:
            httpGet:
              path: /api/health # Updated path
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/ready # Assuming /api/ready for readiness, similar to /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: token-storage
              mountPath: /app/internal/repository/ # Mount the volume here
      volumes:
        - name: token-storage
          emptyDir: {} # Use an emptyDir for temporary storage
