apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # L'email sera utilisé pour les notifications d'expiration.
    email: axel.antunes@hotmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Un Secret pour stocker la clé privée du compte ACME
      name: letsencrypt-staging-private-key
    solvers:
      # Utilise le challenge HTTP-01 qui fonctionne avec l'Ingress NGINX
      - http01:
          ingress:
            class: nginx