package handlers

import (
	"CapIot-api/internal/models"  // Import your actual module name
	"CapIot-api/internal/service" // Import your actual module name
	"database/sql"
	"encoding/json"
	"fmt"
	mqtt "github.com/eclipse/paho.mqtt.golang"
	"github.com/gorilla/mux"
	"log"
	"net/http"
	"strings"
	"time"
)

// MqttHandler struct holds the necessary services for processing MQTT messages
type MqttHandler struct {
	deviceService service.DeviceService // Use the interface type
	mqttClient    mqtt.Client
}

// NewMqttHandler creates a new MqttHandler instance, now taking DeviceService and mqtt.Client
func NewMqttHandler(deviceService service.DeviceService, mqttClient mqtt.Client) *MqttHandler { // Use the interface type here
	return &MqttHandler{
		deviceService: deviceService,
		mqttClient:    mqttClient, // Store the MQTT client
	}
}

// componentInfo represents the structure of each component in the availability message
type ComponentInfo struct {
	ComponentID      string  `json:"component_id"` // This is the unique ID generated by the device
	ComponentName    string  `json:"component_name"`
	ComponentType    string  `json:"component_type"`
	ComponentSubtype string  `json:"component_subtype,omitempty"`
	MinThreshold     float64 `json:"min_threshold,omitempty"`
	MaxThreshold     float64 `json:"max_threshold,omitempty"`
	ComponentStatus  string  `json:"component_status"`
	MaxRunningHours  int     `json:"max_running_hours,omitempty"` // Incoming as int
}

// AvailabilityPayload reflects the structure sent by the Node.js simulator for both availability and LWT
type AvailabilityPayload struct {
	DeviceID   string          `json:"device_id"`
	Status     string          `json:"status"`
	Timestamp  string          `json:"timestamp"`
	Components []ComponentInfo `json:"components,omitempty"`
}

// AlertPayload reflects the structure sent by the Node.js simulator
type AlertPayload struct {
	DeviceID    string `json:"device_id"`
	ComponentID string `json:"component_id"`
	Alert       string `json:"alert"`
	Timestamp   string `json:"timestamp"`
}

// HandleDeviceAvailability gère le message de disponibilité de l'appareil et effectue le provisionnement
func (h *MqttHandler) HandleDeviceAvailability(client mqtt.Client, msg mqtt.Message) {
	var payload AvailabilityPayload
	if err := json.Unmarshal(msg.Payload(), &payload); err != nil {
		log.Printf("Error unmarshalling availability message: %v", err)
		return
	}

	deviceID := payload.DeviceID
	log.Printf("Received availability message for device: %s", deviceID)

	// Begin a transaction for all device and component operations
	tx, err := h.deviceService.BeginTransaction()
	if err != nil {
		log.Printf("Error beginning transaction: %v", err)
		return
	}
	// Defer rollback. If the function completes without error, commit will be called.
	// If an error occurs, the deferred rollback will be executed.
	defer func() {
		if r := recover(); r != nil { // Handle panics
			tx.Rollback()
			panic(r)
		} else if err != nil { // Check if 'err' was set during the function's execution
			tx.Rollback()
		} else {
			tx.Commit()
		}
	}()

	// Check if the device already exists. If not, create it.
	// Pass the transaction to the service method.
	_, err = h.deviceService.GetDeviceByID(deviceID) // This is a read operation, no need for tx here
	if err != nil {
		if err == sql.ErrNoRows { // Device not found, create it
			log.Printf("Device '%s' not found. Creating a new device record.", deviceID)
			newDevice := &models.Device{
				DeviceID:  deviceID,
				Status:    string(models.OperationalStatus(payload.Status)),
				CreatedAt: time.Now(),
			}
			// Pass the transaction to CreateDevice
			if err = h.deviceService.CreateDevice(tx, newDevice); err != nil {
				log.Printf("Error creating device '%s': %v", deviceID, err)
				return // Return on critical error, defer will rollback
			}
		} else { // Genuine database error
			log.Printf("Error checking for existing device '%s': %v", deviceID, err)
			return // Critical error, stop processing, defer will rollback
		}
	} else { // Device exists, update its status.
		// Pass the transaction to UpdateDeviceLastSeenAndStatus
		if err = h.deviceService.UpdateDeviceLastSeenAndStatus(tx, deviceID, models.OperationalStatus(payload.Status)); err != nil {
			log.Printf("Error updating device '%s' status: %v", deviceID, err)
			// Do NOT return here, continue processing components even if status update fails
			// The transaction will still rollback if a later component operation fails.
		}
	}

	// Iterate through the components sent by the device
	// Iterate through the components sent by the device
	for _, comp := range payload.Components {
		// Use the ID provided by the device to check for an existing component
		existingComponent, getErr := h.deviceService.GetComponentByID(comp.ComponentID) // Read operation, no tx needed here
		if getErr != nil && getErr == sql.ErrNoRows {                                   // Component with this ID does not exist, so we create it.
			newComponent := &models.Component{
				ComponentID:      comp.ComponentID, // Use the ID provided by the device (already unique)
				ComponentName:    comp.ComponentName,
				ComponentType:    comp.ComponentType,
				ComponentSubtype: comp.ComponentSubtype,
				ComponentStatus:  comp.ComponentStatus,
			}

			// Correctly handle optional fields and type conversion by creating temporary variables
			if comp.MinThreshold != 0 { // Assuming 0 means not provided/default for thresholds
				val := comp.MinThreshold
				newComponent.MinThreshold = &val
			}
			if comp.MaxThreshold != 0 {
				val := comp.MaxThreshold
				newComponent.MaxThreshold = &val
			}
			if comp.MaxRunningHours != 0 { // Assuming 0 means not provided/default for running hours
				val := int32(comp.MaxRunningHours) // Explicitly convert int to int32
				newComponent.MaxRunningHours = &val
			}

			// Pass the transaction to the service methods for atomic operations
			if _, err = h.deviceService.CreateComponent(tx, newComponent); err != nil {
				log.Printf("Error creating component '%s': %v", comp.ComponentID, err)
				// 'err' is now set, deferred rollback will handle it
				return
			}

			if err = h.deviceService.LinkcomponentToDevice(tx, deviceID, newComponent.ComponentID); err != nil {
				log.Printf("Error linking component '%s' to device '%s': %v", newComponent.ComponentID, deviceID, err)
				// 'err' is now set, deferred rollback will handle it
				return
			}

		} else if getErr != nil { // A genuine database error occurred (not just "no rows")
			log.Printf("Error checking for existing component '%s': %v", comp.ComponentID, getErr)
			err = getErr // Assign the specific error to the outer 'err' for deferred rollback
			return       // Return on critical error, defer will rollback
		} else { // Component already exists. Update its status and other relevant fields.
			log.Printf("Component '%s' already exists. Updating its status to '%s'.", existingComponent.ComponentID, comp.ComponentStatus)

			// Update component status within the transaction
			if err = h.deviceService.UpdateDeviceComponentStatus(tx, existingComponent.ComponentID, comp.ComponentStatus); err != nil {
				log.Printf("Error updating component status for '%s': %v", existingComponent.ComponentID, err)
				// 'err' is now set, deferred rollback will handle it
				return // Return on error, defer will rollback
			}
		}
	}
}

// SetStatus is an HTTP handler that updates the status of a given device via MQTT
func (h *MqttHandler) SetStatus(w http.ResponseWriter, r *http.Request) {
	log.Printf("Received request to set status for device\n")
	vars := mux.Vars(r)
	deviceID := vars["deviceID"]
	if deviceID == "" {
		http.Error(w, "Missing deviceID in URL", http.StatusBadRequest)
		return
	}

	var req struct {
		Status string `json:"status"`
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid JSON payload", http.StatusBadRequest)
		return
	}

	if req.Status == "" {
		http.Error(w, "Missing status in request body", http.StatusBadRequest)
		return
	}

	// Look for location_id in db
	location, err := h.deviceService.GetLocationByDeviceID(deviceID)
	if err != nil {
		if err == sql.ErrNoRows {
			log.Printf("Device '%s' not found or not linked to a location in DB.\n", deviceID)
			http.Error(w, "Device not found or not linked to a location", http.StatusNotFound)
			return
		}
		log.Printf("Error retrieving location for device '%s': %v\n", deviceID, err)
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}

	var locationID int // Default value is 0
	if location != nil && location.ID != nil {
		locationID = *location.ID // Correctly dereference the pointer
	}

	// Construct MQTT payload
	payload := map[string]interface{}{
		"device_id": deviceID,
		"status":    req.Status,
	}
	if locationID != 0 {
		payload["location_id"] = locationID
	}

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		log.Printf("Error marshalling MQTT payload: %v", err)
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}

	// Publish to MQTT
	topic := "devices/status/" + deviceID
	token := h.mqttClient.Publish(topic, 0, false, payloadBytes) // QoS 0, not retained
	token.Wait()
	if token.Error() != nil {
		log.Printf("MQTT publish error: %v", token.Error())
		http.Error(w, "Failed to publish MQTT message", http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(fmt.Sprintf("Status '%s' set for device '%s'", req.Status, deviceID)))
}

// HandleDeviceStatus is now primarily for status updates sent by the device itself, NOT LWT.
func (h *MqttHandler) HandleDeviceStatus(client mqtt.Client, msg mqtt.Message) {
	log.Printf("Received status update on topic: %s, message: %s\n", msg.Topic(), string(msg.Payload()))

	parts := strings.Split(msg.Topic(), "/")
	// Expected format: devices/status/deviceID
	if len(parts) != 3 || parts[0] != "devices" || parts[1] != "status" {
		log.Printf("Received message on unexpected status topic format: %s\n", msg.Topic())
		return
	}

	deviceID := parts[2] // Device ID is the third part

	var statusPayload struct {
		DeviceID   string  `json:"device_id"`
		Status     string  `json:"status"`
		LocationID float64 `json:"location_id,omitempty"` // Incoming as float64
	}

	if err := json.Unmarshal(msg.Payload(), &statusPayload); err != nil {
		log.Printf("Error unmarshalling JSON for device status on topic '%s': %v\n", msg.Topic(), err)
		return
	}

	// Ensure deviceID from topic matches payload, for safety
	if statusPayload.DeviceID != deviceID {
		log.Printf("Warning: DeviceID mismatch between topic (%s) and payload (%s) for status update on topic %s\n",
			deviceID, statusPayload.DeviceID, msg.Topic())
		// You might choose to return here if a mismatch is critical. For now, we'll proceed with topic's deviceID.
	}

	log.Printf("Received status '%s' from device '%s'.\n", statusPayload.Status, deviceID)

	// Begin a transaction for status updates
	tx, err := h.deviceService.BeginTransaction()
	if err != nil {
		log.Printf("Error beginning transaction for status update: %v", err)
		return
	}
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
			panic(r)
		} else if err != nil {
			tx.Rollback()
		} else {
			tx.Commit()
		}
	}()

	// Update device's operational status in the database
	// Pass the transaction to the service method
	if err = h.deviceService.UpdateDeviceOperationalStatus(tx, deviceID, models.OperationalStatus(statusPayload.Status)); err != nil {
		log.Printf("Error updating device '%s' operational status to '%s': %v", deviceID, statusPayload.Status, err)
		return // Return on error, defer will rollback
	}
	// Also update last seen for general status updates
	// Pass the transaction to the service method
	if err = h.deviceService.UpdateDeviceLastSeenAndStatus(tx, deviceID, models.OperationalStatus(statusPayload.Status)); err != nil {
		log.Printf("Error updating device '%s' last seen from status update: %v\n", deviceID, err)
		return // Return on error, defer will rollback
	}

	// If device sends "Running" status and has a location_id, send back the config
	if statusPayload.Status == "Running" && statusPayload.LocationID != 0 {
		// Retrieve all components linked to this device from your database
		linkedComponents, getCompErr := h.deviceService.GetcomponentsByDeviceID(deviceID) // Read operation, no tx
		if getCompErr != nil {
			log.Printf("Error getting linked components for device '%s': %v", deviceID, getCompErr)
			// Set err to getCompErr so defer will rollback if this was the first error
			err = getCompErr
			return // Return on error, defer will rollback
		}

		// Iterate through linked components and send their config
		for _, component := range linkedComponents {
			minThreshold := 0.0
			if component.MinThreshold != nil {
				minThreshold = *component.MinThreshold
			}
			maxThreshold := 0.0
			if component.MaxThreshold != nil {
				maxThreshold = *component.MaxThreshold
			}

			// Send individual component config to the device
			if err = h.SetDeviceConfig(deviceID, component.ComponentID, minThreshold, maxThreshold); err != nil {
				log.Printf("Error re-sending config for component '%s' to device '%s': %v\n", component.ComponentID, deviceID, err)
				// Do not return here, try to send other configs.
				// The transaction for DB updates is separate from MQTT publish errors.
			} else {
				log.Printf("Resent config to device '%s' for component '%s' (Min: %.2f, Max: %.2f) after 'Running' status.\n",
					deviceID, component.ComponentID, minThreshold, maxThreshold)
			}
		}

		// Optionally, send a generic "start monitoring" or acknowledgement
		// based on the original Node.js logic that expected a response with location_id.
		// This is a bit redundant if you're sending individual configs, but kept for compatibility.
		payload := map[string]interface{}{
			"device_id":   deviceID,
			"location_id": int(statusPayload.LocationID), // Send as int
		}
		payloadBytes, marshalErr := json.Marshal(payload)
		if marshalErr != nil {
			log.Printf("Error marshalling JSON payload for monitoring start acknowledgement: %v", marshalErr)
			// Set err to marshalErr for deferred rollback if needed
			err = marshalErr
			return
		}

		// Send back to the specific device's config topic to trigger data monitoring if needed
		topic := fmt.Sprintf("devices/config/%s", deviceID) // Using config topic for consistency with simulator
		token := h.mqttClient.Publish(topic, 0, false, payloadBytes)
		token.Wait()
		if token.Error() != nil {
			log.Printf("Error publishing MQTT message to acknowledge monitoring start: %v", token.Error())
			// This is an MQTT publish error, not a DB error, so it doesn't necessarily trigger DB rollback.
		} else {
			log.Printf("MQTT acknowledgement published to %s: %s", topic, payloadBytes)
		}
	} else if statusPayload.Status != "Running" {
		log.Printf("Device '%s' status is '%s'. No monitoring start initiated.", deviceID, statusPayload.Status)
	}
}

func (h *MqttHandler) SetDeviceConfig(deviceID string, ComponentID string, minThreshold float64, maxThreshold float64) error {
	if deviceID == "" {
		return fmt.Errorf("deviceID cannot be empty")
	}
	if ComponentID == "" {
		return fmt.Errorf("ComponentID cannot be empty")
	}

	mqttPayload := map[string]interface{}{
		"component_id":  ComponentID,
		"min_threshold": minThreshold,
		"max_threshold": maxThreshold,
	}

	payloadBytes, err := json.Marshal(mqttPayload)
	if err != nil {
		log.Printf("Error marshalling MQTT payload for config: %v", err)
		return fmt.Errorf("failed to marshal MQTT payload: %w", err)
	}

	topic := "devices/config/" + deviceID
	token := h.mqttClient.Publish(topic, 0, false, payloadBytes) // QoS 0, not retained for configuration commands
	token.Wait()
	if token.Error() != nil {
		log.Printf("MQTT publish error for config: %v", token.Error())
		return fmt.Errorf("failed to publish MQTT message: %w", token.Error())
	}

	log.Printf("Configuration sent for component '%s' on device '%s' with Min: %.2f, Max: %.2f", ComponentID, deviceID, minThreshold, maxThreshold)
	return nil
}

func (h *MqttHandler) HandleDeviceAlert(client mqtt.Client, message mqtt.Message) {
	log.Printf("Received alert on topic: %s, message: %s\n", message.Topic(), string(message.Payload()))

	parts := splitTopic(message.Topic())
	// Expected format: devices/alert/deviceID
	if len(parts) != 3 || parts[0] != "devices" || parts[1] != "alert" {
		log.Printf("Received message on unexpected alert topic format: %s (Expected 'devices/alert/deviceID')\n", message.Topic())
		return
	}

	deviceIDFromTopic := parts[2] // Device ID is the third part

	var payload AlertPayload
	err := json.Unmarshal(message.Payload(), &payload)
	if err != nil {
		log.Printf("Error unmarshalling JSON for device alert on topic '%s': %v\n", message.Topic(), err)
		return
	}

	// Validate deviceID from topic matches payload
	if payload.DeviceID != deviceIDFromTopic {
		log.Printf("Warning: DeviceID mismatch between topic (%s) and payload (%s) for alert on topic %s\n",
			deviceIDFromTopic, payload.DeviceID, message.Topic())
		// Decide if you want to proceed or return here based on strictness
	}

	log.Printf("Received alert '%s' from device '%s' (component '%s', timestamp '%s').\n",
		payload.Alert, payload.DeviceID, payload.ComponentID, payload.Timestamp)

	// Begin a transaction for alert handling (e.g., logging to DB)
	tx, err := h.deviceService.BeginTransaction()
	if err != nil {
		log.Printf("Error beginning transaction for alert: %v", err)
		return
	}
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
			panic(r)
		} else if err != nil {
			tx.Rollback()
		} else {
			tx.Commit()
		}
	}()

	// Pass payload data to the service handler
	// Pass the transaction to the service method
	if err = h.deviceService.HandleDeviceAlert(tx, payload.ComponentID, payload.Alert); err != nil { // Assuming this matches your service interface
		log.Printf("Error handling device alert for component '%s': %v", payload.ComponentID, err)
		return // Return on error, defer will
	}
}

func (h *MqttHandler) ResetTimer(writer http.ResponseWriter, request *http.Request) {
	vars := mux.Vars(request)
	deviceID := vars["deviceID"]
	componentID := vars["ComponentID"] // This is the component_name from the URL, not the unique ID

	if deviceID == "" || componentID == "" {
		http.Error(writer, "Missing deviceID or ComponentID (component_name) in URL", http.StatusBadRequest)
		return
	}

	// The Node.js simulator expects commands on "devices/commands/{deviceID}"
	// and the command type in the payload.
	topic := fmt.Sprintf("devices/commands/%s", deviceID)

	// Create payload for the command
	payload := map[string]interface{}{
		"command":      "reset_component_timer", // Command type
		"device_id":    deviceID,
		"component_id": componentID, // This is the component_name from the URL
	}
	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		log.Printf("Error marshalling reset timer payload: %v", err)
		http.Error(writer, "Internal server error", http.StatusInternalServerError)
		return
	}

	// Publish the message
	token := h.mqttClient.Publish(topic, 0, false, payloadBytes)
	token.Wait()

	if token.Error() != nil {
		log.Printf("MQTT publish error for reset timer: %v", token.Error())
		http.Error(writer, "Failed to publish reset timer command", http.StatusInternalServerError)
		return
	}

	writer.WriteHeader(http.StatusOK)
	writer.Write([]byte(fmt.Sprintf("Reset timer command sent for device '%s', component '%s'", deviceID, componentID)))
}

// Helper function to split the MQTT topic
func splitTopic(topic string) []string {
	return strings.Split(topic, "/")
}
