apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  namespace: mqtt-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt # changed to match the service selector
  template:
    metadata:
      labels:
        app: mqtt # changed to match the service selector
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.18 # example of a specific version
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-configmap