apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  type: LoadBalancer   # 👈 makes it externally accessible
  selector:
    app: mqtt
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
