apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  namespace: capiot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.18
          ports:
            - containerPort: 1883
            - containerPort: 9001 # Keep this if your service exposes it
          volumeMounts:
            - name: mosquitto-config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf # Mount only the specific file
      volumes:
        - name: mosquitto-config-volume
          configMap:
            name: mosquitto-config # Reference the ConfigMap created above
